env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-fakedns
    commit_author:
      name: hupe1980
    homepage:  https://github.com/hupe1980/fakedns
    description: Tiny DNS proxy for Penetration Testers and Malware Analysts
    license: MIT
    test: |
      system "#{bin}/fakedns -v"
scoop:
  bucket:
    owner: hupe1980
    name: fakedns-bucket
  commit_author:
      name: hupe1980
  homepage:  https://github.com/hupe1980/fakedns
  description: Tiny DNS proxy for Penetration Testers and Malware Analysts
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/fakedns
    maintainer: Frank Hübner <frankhuebner1980@gmail.com>
    description: Tiny DNS proxy for Penetration Testers and Malware Analysts
    license: MIT
    formats:
    - apk
    - deb
    - rpm
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Tiny DNS proxy for Penetration Testers and Malware Analysts
    description: |
      Tiny DNS proxy for Penetration Testers and Malware Analysts
      
      Features:
      * Regular Expression based DNS server
      * IPV4 & IPV6
      * DNS Rebinding
      * DNS Round-Robin
      * Upstream DNS Resolver
      
      Usage: fakedns [domains] [flags]
      
      Examples:
      * IPV4: fakeDNS example.org --ipv4 127.0.0.1
      * Wildcards: fakeDNS example.* --ipv4 127.0.0.1
      * RoundRobin: fakeDNS example.org --ipv4 127.0.0.1,10.10.10.10
      * Rebind: fakeDNS example.org --ipv4 127.0.0.1 --rebind-v4 10.10.10
      * Upstream: fakeDNS example.org --ipv4 127.0.0.1 --upstream 8.8.8.8
    grade: stable
    confinement: strict
    publish: true